/*
 * Management API
 *
 * The version of the OpenAPI document: 1
 * Contact: developer-experience@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adyen.model.management;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new AdditionalSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalSettingsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Address.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Address2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AllowedOrigin.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AllowedOriginsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Amount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Amount2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AndroidApp.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AndroidAppsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AndroidCertificate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AndroidCertificatesResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ApiCredential.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ApiCredentialLinks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ApplePayInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new BcmcInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new BillingEntitiesResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new BillingEntity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CardholderReceipt.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CartesBancairesInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Company.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CompanyApiCredential.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CompanyLinks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CompanyUser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Connectivity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Contact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateAllowedOriginRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateApiCredentialResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateCompanyApiCredentialRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateCompanyApiCredentialResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateCompanyUserRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateCompanyUserResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateCompanyWebhookRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateMerchantApiCredentialRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateMerchantRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateMerchantResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateMerchantUserRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateMerchantWebhookRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateUserResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Currency.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CustomNotification.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new DataCenter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new EventUrl.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ExternalTerminalAction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new GenerateApiKeyResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new GenerateClientKeyResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new GenerateHmacKeyResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new GiroPayInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new GooglePayInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Gratuity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Hardware.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new IdName.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new InstallAndroidAppDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new InstallAndroidCertificateDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new InvalidField.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new JSONObject.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new JSONPath.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new KlarnaInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Links.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new LinksElement.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ListCompanyApiCredentialsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ListCompanyResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ListCompanyUsersResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ListExternalTerminalActionsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ListMerchantApiCredentialsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ListMerchantResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ListMerchantUsersResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ListStoresResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ListTerminalsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ListWebhooksResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Logo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new MeApiCredential.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Merchant.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new MerchantLinks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new MinorUnitsMonetaryValue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ModelConfiguration.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ModelFile.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Name.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Name2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Nexo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new OfflineProcessing.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Opi.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new OrderItem.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaginationLinks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PayPalInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentMethod.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentMethodResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentMethodSetupInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PayoutSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PayoutSettingsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PayoutSettingsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Profile.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ReceiptOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ReceiptPrinting.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ReleaseUpdateDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new RequestActivationResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new RestServiceError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ScheduleTerminalActionsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ScheduleTerminalActionsRequestActionDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ScheduleTerminalActionsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Settings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ShippingLocation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ShippingLocationsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ShopperStatement.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Signature.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new SofortInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Store.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new StoreCreationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new StoreCreationWithMerchantCodeRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new StoreSplitConfiguration.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Surcharge.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new SwishInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Terminal.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new TerminalActionScheduleDetail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new TerminalModelsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new TerminalOrder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new TerminalOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new TerminalOrdersResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new TerminalProduct.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new TerminalProductsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new TerminalSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new TestCompanyWebhookRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new TestOutput.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new TestWebhookRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new TestWebhookResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Timeouts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UninstallAndroidAppDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UninstallAndroidCertificateDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UpdatableAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UpdateCompanyApiCredentialRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UpdateCompanyUserRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UpdateCompanyWebhookRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UpdateMerchantApiCredentialRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UpdateMerchantUserRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UpdateMerchantWebhookRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UpdatePaymentMethodInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UpdatePayoutSettingsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UpdateStoreRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Url.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new User.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Webhook.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new WebhookLinks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new WifiProfiles.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
