/*
 * Adyen Checkout API
 *
 * The version of the OpenAPI document: 69
 * Contact: developer-experience@adyen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adyen.model.checkout;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new AccountInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AcctInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AchDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalData3DSecure.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataAirline.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataCarRental.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataCommon.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataLevel23.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataLodging.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataOpenInvoice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataOpi.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataRatepay.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataRetry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataRisk.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataRiskStandalone.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataSubMerchant.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataTemporaryServices.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AdditionalDataWallets.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Address.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AfterpayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AmazonPayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Amount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AndroidPayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ApplePayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ApplePaySessionResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ApplicationInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new AuthenticationData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Avs.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new BacsDirectDebitDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new BankAccount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new BillDeskDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new BlikDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new BrowserInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Card.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CardBrandDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CardDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CardDetailsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CardDetailsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CellulantDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutAwaitAction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutBalanceCheckRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutBalanceCheckResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutCancelOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutCancelOrderResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutCreateOrderRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutCreateOrderResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutOrder.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutOrderResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutQrCodeAction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutRedirectAction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutSDKAction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutSessionInstallmentOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutThreeDS2Action.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutUtilityRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutUtilityResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CheckoutVoucherAction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CommonField.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Company.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateApplePaySessionRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateCheckoutSessionRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateCheckoutSessionResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreatePaymentAmountUpdateRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreatePaymentCancelRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreatePaymentCaptureRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreatePaymentLinkRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreatePaymentRefundRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreatePaymentReversalRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new CreateStandalonePaymentCancelRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new DetailsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new DeviceRenderOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new DokuDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new DonationResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new DotpayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new DragonpayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new EcontextVoucherDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ExternalPlatform.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ForexQuote.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new FraudCheckResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new FraudResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new GenericIssuerPaymentMethodDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new GiropayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new GooglePayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new IdealDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new InputDetail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new InstallmentOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Installments.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new InstallmentsNumber.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Item.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new KlarnaDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new LineItem.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Mandate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new MasterpassDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new MbwayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new MerchantDevice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new MerchantRiskIndicator.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new MobilePayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ModelConfiguration.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new MolPayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Name.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new OpenInvoiceDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PayPalDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PayUUpiDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PayWithGoogleDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentAmountUpdateResource.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentCancelResource.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentCaptureResource.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentCompletionDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentDetailsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentDonationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentDonationRequestPaymentMethod.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentLinkResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentMethod.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentMethodGroup.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentMethodIssuer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentMethodsRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentMethodsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentRefundResource.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentResponseAction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentReversalResource.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentSetupRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentSetupResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentVerificationRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new PaymentVerificationResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Phone.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new RatepayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Recurring.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new RecurringDetail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ResponseAdditionalData3DSecure.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ResponseAdditionalDataBillingAddress.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ResponseAdditionalDataCard.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ResponseAdditionalDataCommon.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ResponseAdditionalDataInstallments.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ResponseAdditionalDataNetworkTokens.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ResponseAdditionalDataOpi.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ResponseAdditionalDataSepa.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ResponsePaymentMethod.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new RiskData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new SDKEphemPubKey.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new SamsungPayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new SepaDirectDebitDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ServiceError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ServiceError2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ShopperInput.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ShopperInteractionDevice.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new Split.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new SplitAmount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new StandalonePaymentCancelResource.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new StoredDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new StoredPaymentMethod.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new StoredPaymentMethodDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new SubInputDetail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ThreeDS2RequestData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ThreeDS2ResponseData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ThreeDS2Result.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ThreeDSRequestData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ThreeDSRequestorAuthenticationInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ThreeDSRequestorPriorAuthenticationInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ThreeDSecureData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UpdatePaymentLinkRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UpiCollectDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new UpiIntentDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new VippsDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new VisaCheckoutDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new WeChatPayDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new WeChatPayMiniProgramDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new ZipDetails.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
